### ISSUE TITLE
Project Dead? - Alternative?

### ISSUE THREAD

**Issue by mr2017x** [Trevelopment/MZD-AIO#109]
Hi Guys,

hope you are all well - is that project dead? How is further planning or is there an alternative given?

Thanks in advance

**Comment by Trevelopment** [comment]
I may make one more update but it is coming to the EOL for this project, why do you need something specific that this doesn't already do?

**Comment by hannad4** [comment]
There are some features that I wish this project could have supported. They are Android Auto features which the stock OEM can do - I can only tell these features because I installed OEM retro-kit on the family car, but not my car: 

1) Offer the Android Auto icon in the top left of the Mazda Connect home screen when you connect your phone as a short cut
2) Allow switching between Android Auto/Mazda Connect via 3 second hold of home button (instead of end call button)
3) When you are on any Mazda Connect screen, pressing the NAV button will navigate to google maps (if you have Mazda Navigation, then this shortcut does not apply)
4) If you are playing music from Android Auto but are on a Mazda Connect screen, pressing the MUSIC button will navigate to Android Auto media playing

With that being said, these are obviously features which I wish were implemented, but they are certainly not _needed_. It is completely reasonable to say that if I desire these things that much, I should just buy the upgrade kit and install it - and I may do that in the future. Anyways, this project has definitely served its purpose in providing a reliable means for modification of the Mazda Connect System. 

I realize how difficult it is to develop something like this in your free time @Trevelopment, and I thank you for your work on the project and sharing it with the world. This has provided value to my vehicle a lot, and I love using my car even more because of it.

**Comment by Trevelopment** [comment]
@hannad4 These features are all very difficult to do with the hacked Android Auto for a myriad of reasons.  Also, the better place to ask for those features would be the repo dedicated to AA found here https://github.com/gartnera/headunit because I don't have a ton of time to develop this project anymore.
And you are welcome, I really enjoyed creating and maintaining this project and I am glad it has improved the driving experience of over a hundred thousand Mazda drivers.

**Comment by mr2017x** [comment]
> I may make one more update but it is coming to the EOL for this project, why do you need something specific that this doesn't already do?

uhm, sad to hear but yes i understand. sadly since android 9 or 10? (over 2 years) aa isn't running in my 2015mazda6 anymore...so that would be a cool thing to go..or drive..:-)

**Comment by bradgreen273241** [comment]
Will this program work on a 2020 mazda 6 signature I want to watch videos and can't figure out how any help would be much appreciated

Sent via the Samsung Galaxy S20 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by cmitch419** [comment]
> @hannad4 These features are all very difficult to do with the hacked Android Auto for a myriad of reasons. Also, the better place to ask for those features would be the repo dedicated to AA found here https://github.com/gartnera/headunit because I don't have a ton of time to develop this project anymore.
> And you are welcome, I really enjoyed creating and maintaining this project and I am glad it has improved the driving experience of over a hundred thousand Mazda drivers.

@Trevelopment I just want you to know that you made my 2016.5 Mazda CX-5 an absolute treat to drive by developing these tweaks.  Thank you again
