### ISSUE TITLE
2016 CX-5 cannot connect to hotspot 

### ISSUE THREAD

**Issue by coolfoil** [Trevelopment/MZD-AIO#19]
Hello there.
I'm trying to connect my car to my hotspot to use Android Auto but I get a network error every time. Everything else is working perfectly and I haven't been able to find a solution online. I could use a USB connection but the USB ports barely charge my phone, so I use an adapter in the center console instead. Any ideas?

**Comment by Trevelopment** [comment]
Unfortunately In many of the CMUs before 2016, including my own, and most of the North American models the WiFi receiver is not properly shielded from electromagnetic interference caused by being to close to the Bluetooth adapter.  This guy said it best here:  http://whrl.pl/ReI3wR
> For those who have any Mazda model below model year 2016 (approximately) and MZD Connect.
> MMC has recognized that the CMU (Connectivity Master Unit, the thing that runs MZD) is defective when it comes to using Bluetooth and Wi-Fi (those who use and pay for Connected Services) together at the same time owners are seeing drop outs or connection issues with BT and or WiFi.
> Basically Visteon the makers of the CMU did not adequately 'shield' the two antenna inside CMU.
> The fix is a modified CMU only installed by your Mazda Dealer.
You must "complain" that you are having connection issues to these device services.
The Dealer may say it is your phone, or the firmware for CMU needs updating, 
this is a waste of time, the Firmware update does not fix a Hardware fault issue.

**Comment by coolfoil** [comment]
Damn that's a shame. Thank you very much though.
