### ISSUE TITLE
Statusbar Speedometer cosmetics

### ISSUE THREAD

**Issue by Kees-V** [Trevelopment/MZD-AIO#21]
First of all:
I am a happy user of of the Statusbas Speedometer 2.8.0 on 59.00.545 EU N, thanks for all your work on this!
In day-to-day use I noticed two small cosmetic issues, which you might be able to solve in a future release.
1 Alignment of the clock and speed readout in the "Offscreen"
![statusbar speedometer on](https://user-images.githubusercontent.com/9340329/45584715-5d1dbc80-b8c8-11e8-872c-ac9ad858c45d.jpg)
![statusbar speedometer offscreen](https://user-images.githubusercontent.com/9340329/45584713-598a3580-b8c8-11e8-91f8-abbe04947835.jpg)
2 When the mobile phone is roaming, the "ROAM" icon overlaps the signal indicator on normal screen
![statusbar speedometer roaming](https://user-images.githubusercontent.com/9340329/45584749-ec2ad480-b8c8-11e8-8554-747952ac5ea3.jpg)

**Comment by Trevelopment** [comment]
you wanna test this out for me? I fixed the off screen but I never get the roam or traffic icons and they are in a separate div but same class name as the other 4 that's why they overlap. So test this out for me you just have to replace `/jci/gui/apps/_speedometer/css/StatusBarSpeedometer.css` and that should do it but let me know if this does the trick.
[StatusBarSpeedometer.css.zip](https://github.com/Trevelopment/MZD-AIO/files/2399791/StatusBarSpeedometer.zip)

**Comment by Kees-V** [comment]
Thanks, that looks so much better!
![offscreenalignmentok](https://user-images.githubusercontent.com/9340329/45835147-c5213800-bcf8-11e8-9fa2-de533f9af279.jpg)
Testing the "ROAM" icon will take a little longer, as the holiday season is over.

**Comment by Kees-V** [comment]
I found some time to roam today. The icons line up nicely now, thanks again for working on this!!
![roam ok](https://user-images.githubusercontent.com/9340329/45918526-be6cff00-be77-11e8-8b17-72a16ca20d48.jpg)

**Comment by Trevelopment** [comment]
Fixed
