### ISSUE TITLE
Audio and performance issues with Pixel 3

### ISSUE THREAD

**Issue by aserper** [Trevelopment/MZD-AIO#31]
Hey there,
Everything worked almost flawless with my old pixel 1. Since I upgraded to the pixel 3 once Google maps is open it completely hijacks the audio, meaning you can't listen to the radio and use maps, you can only hear the directions, not even Spotify works. If you want to listen to music AND navigate you must play a song on Spotify (or any other music app) and then start the navigation (as I said, radio doesn't work at all). This also introduced some performance issues where the audio is very choppy every time there are some "heavy rendering" on the map. These issues never happened before with the Pixel 1.

P.s tried to upgrade to 2.8.1, problems still exist.

Running on a NA abarth 124 spider.

**Comment by Trevelopment** [comment]
Have you tried pressing the :star: fav button when you lose audio focus to Google Maps?

**Comment by aserper** [comment]
Thanks for your reply! No, I did not (is there a page somewhere with
explanations about those buttons and tricks? I will try it soon and see if
it solves the problem. Will the star button solve the choppy audio as well?
It is it a different issue?

**Comment by Trevelopment** [comment]
yea someone is working on that issue over in the [headunit repository](https://github.com/Trevelopment/headunit) but no need to open another issue over there.

**Comment by iainheng** [comment]
I am having the similar issue with my Pixel 3XL too. The audio stuttering almost every single turn on the map. The performance was far better on my original Pixel 1. 

Both Google Maps and Waze suffered the same problem with noticable lags when clicking between menu items. 

Tried disable adaptive battery optimizations as well but problem still persists.

Any suggestions or optimizations?

**Comment by Paulsword** [comment]
Too bad. I just changed my IPhone for a new Pixel 3 to use AA (assuming no device would be better than Google's at working with Android) and now that's what I get: no chance to shift from AA to radio and back (as it would lose audio), Google Maps suddenly running backwards after receiving a new voice command, Waze losing voice, with Spotify music wavering high and low..
Is this all happening with Pixel 3 only?
Please help!

**Comment by Trevelopment** [comment]
You can shift to the radio by pressing the fav :star: button
You can stop running backwards by popping out your nav SD card
The Waze issues are specific to the Waze app not android auto and everyone is experiencing them so Waze needs to fix that.  That includes the volume wavering issue it is caused by the Waze app I cant even use Waze anymore because of it.

**Comment by Paulsword** [comment]
Thank you so much @Trevelopment. I will give feedback!

**Comment by Paulsword** [comment]
Yes, great! The fav button solved the problem. Now I can safely shift to the radio and back to Spotify whenever I want. Also, music apps work flawlessly with Google Maps voice on, while radio still needs to be recalled by fav button every time GM speaks (ok, if that has to be, it's not a big deal for me). Moreover, no backward running on GM, after built-in system card has been removed.
Well, it looks like Pixel 3 phones are not an issue per se.
Thanks again.

**Comment by iainheng** [comment]
@Paulsword Did you experience any music stuttering when navigating with Google Maps or Waze while listening to Spotify? I have very bad audio stuttering every time the map rotates when navigating. (only when playing music in Android Auto. Works fine if play with Mazda FM radio).

**Comment by Paulsword** [comment]
As mentioned, Waze issues are more like wavering high and low, and we will wait for a fix by Waze (I didn't even give it a try today). Stuttering in Google Maps sounds more like a data load issue to me, and I haven't suffered from that, if not occasionally. Cable quality might have something to do with it? Keep in mind that I also previously uninstalled all tweaks, searching for a fix for my issues, including speedometer, though now I am not sure whether this can be helpful/necessary or not. I am not an expert, but I guess your main focus should be on every setting affecting the amount of data transfer between phone and info system..

**Comment by Trevelopment** [comment]
you can fix the waze issue by disabling the voice navigation in the app on your phone.  That setting is separate from the voice directions setting in the CMU

**Comment by aserper** [comment]
I shall try that. I do have to say that in my other car that has AA built into it originally there are no issues, also, I didn't have any issues with my old pixel 1. With the pixel 3 it's impossible to listen to music and have navigation on at the same time because it gets really jittery. I tried using my wife's pixel 1 and there are no issues

**Comment by iainheng** [comment]
Exactly the same issue with mine as well. I was using OG Pixel before I switched to Pixel 3XL. It was working fine with OG Pixel with very minor stuttering sometimes. Pixel 3XL audio stuttering is too frequent which happen almost every turn (left or right) that cause the map rotates. 

I have tried turn off battery optimizations and reset the phone itself but the problem is persist. 

Btw, the audio stuttering only happen when navigating with Google Maps or Waze and playing USB audios and Spotify. Audio is fine if I listen to MZD's FM radio. I can see the FPS of Google Map/Waze is heavily slowed down when playing audio in AA simultaneously.

**Comment by aserper** [comment]
Update: tried disabling optimizations and no change. Just like the person above this comment ☝️

**Comment by Trevelopment** [comment]
@aserper what audio source are you listening to when it is stuttering USB or Spotify?  I think that connecting the USB stick with music on it after the system has booted up all the way helps reduce the stuttering a bit.  I am beginning to think this is an issue with the data transfer speed of the stock USB hub and that is why the official AA requires the upgraded hub.  If I can figure out [this issue with libusb](https://github.com/gartnera/headunit/issues/147) and get AA running on v70 maybe we can test if there is still stuttering when using our version of AA with the upgraded hub,

**Comment by aserper** [comment]
It happens when I listen to Spotify and use maps to navigate. My work around is to press the AA home button and see the navigation instructions on the main screen, that keeps the rendering low and doesn't make the music go choppy. I'm experiencing exactly what @iainheng described - word for word.

**Comment by stefanoceruti** [comment]
I have the same issue with my OnePlus 6. It doens't happen all the time, but it's quite frequent (85% of the time)
When the issue happens, I need to stay either on the Andorid Auto home page or just tgo to the Music page otherwise I cannot hear the song since it's breaking.

**Comment by tmaiaroto** [comment]
Well, I'm late to the party 😃 same deal. Pixel 3. Any other ideas? I can't seem to get the wifi AA connection working, but I'm wondering if that would push data faster?

It's USB 2, right? So it could theoretically be slower than the new kit Mazda has which is USB 3.

**Comment by cdeutsch** [comment]
Same boat here with Pixel 3 (not sure why this issue is closed?)

I swear I didn't have the issue until I updated to AIO 2.8.4 (from 2.7.9), but maybe I hadn't used maps and Spotify with my Pixel 3 yet (I don't drive the Miata in the winter)

**Comment by cdeutsch** [comment]
I re-installed 2.7.9 which installs Android Auto 1.08.

It only skipped twice (really quickly) during my 15 minutes test drive with Google Maps running and Spotify playing. Big improvement.

Issue must be a combination of Pixel 3 and Android Auto (which is a shame because Google controls all of that 😑)

**Comment by mlwish** [comment]
I had exactly the same issue with my OnePlus 6T.
When my AA is in music or home page, the music plays normally,
However, if I switch AA to Maps app(both Google Maps and Waze), the music starts stuttering.
I've tried several options like changing cables, turn off wifi, reset bluetooth and etc.
Neither works.

I do notice that if I use Maps to navigate, it doesn't stutter that much.

If I open the Map without actually navigating, it stutters 90% especially when I drive fast or make a turn.

Hope there will be a fix on the next AA release.

**Comment by Trevelopment** [comment]
There is a reason you have to get the upgraded USB hub to run the official AA/CP and that is because the stock hub has a shared USB port configuration while the upgraded hub changes that into an independent configuration. (actually I think stock might even split one bus between the 2 USB ports AND the SD card)
> Much like a data network, a USB port has limited bandwidth that it can share between devices. Usage varies from device to device. In an independent USB port, virtually all bandwidth – a total of 480 Mbps for 2.0 ports, and as much as 5 Gbps for 3.0 ports – is available for a single device. USB standards devote 10 percent of all data bandwidth to control, and reserve the rest for device use. In a shared environment, that bandwidth is shared between all devices. High-bandwidth peripherals, such as Web cameras or audio recorders [or a phone running Android Auto], may experience lower performance when connected to a shared USB port.
So let me ask, do you have anything using the other USB port?

**Comment by hannad4** [comment]
The thing is, this issue wasn't present with certain devices (I had the HTC 10 which had lower specs than my Pixel 3). The lagging only persisted with my Pixel 3. I don't remember what AA version I was running with my HTC, but I think it was one version number up from the current one. Either way, it was working fine with the "old" hub, so I am not sure that the USB hub is the reason for the lagginess. I always have my phone cable (and only my phone cable) plugged in as well, so the other port is unoccupied.

**Comment by tmaiaroto** [comment]
I thought maybe it was due to the USB 2.0, but I'm beginning to doubt that. Pushing low resolution video and audio shouldn't really require that much to stream. Even my 4k smart TV only has a 100mbps wired connection (funny the wireless is faster) and it's perfectly fine. So common sense here says no.

If you go into developer settings in the Android Auto app on your phone (first from the left hamburger menu > settings, then right 3 dot menu > developer settings) it allows you to choose the video resolution. I forced the lowest, 480p. I feel like this may have helped a little bit. I still get stuttering though. I've grown used to listening to podcasts from the home menu and listening to Waze for directions and hazards.

The answer of course would be "yes" to the question if we have other things sharing the USB. There's a USB stick in there for the AIO tweaks :) This is part of why I was wondering if WiFi would improve things. For starters, it would no longer share bandwidth (well, maybe, there's caveats there).

I believe the WiFi doesn't work right now because the IP address is assigned different each time. I'm hoping this one https://github.com/gartnera/headunit/pull/153 gets merged soon and there's a new build. I still have to set things up for development and see if I can just get the patch, but I have such limited time unfortunately.

If that doesn't work, I'd probably need a whole boat load of more time to see what else can be done. I simply can't believe that the bandwidth isn't enough. It just doesn't make sense. I also saw the buttons to hold for the resource usage. Nothing seems to be maxed out. I'm not even sure that swap file is needed (though oddly enough it complains about not finding fstab when I go to unmount -- so I don't even know if it's even mounting anything?).

**Comment by jairgs** [comment]
I think this is an issue related to graphics processing and/or memory. 

Quick fix: zoom in a bit in the google maps screen (bottom right).

**Comment by tmaiaroto** [comment]
If you're zoomed in it's also likely pushing less data. Ive tried just putting maps in the background too. That helps, but lately my connection with Android auto has been super flakey. ... I may have an issue with swap space for that one.

Regardless, Trez is correct. It's the USB that's limited. Though technically speaking Android Auto shouldn't really need more bandwidth. I really am surprised if that's the case. I'm hoping there's options somehow to reduce the data transfer, but more importantly I'm curious if there's even a way to just see what that transfer is and measure before embarking on any quests.

USB 3.0 is rarely a requirement for things like that. It's mainly a benefit to transfer files faster so it's great for external storage...but for something like this there really should be plenty of bandwidth. Or Android Auto is just really poorly built.

**Comment by cdeutsch** [comment]
In the market to upgrade my Pixel 3.

Does the Pixel 4(a) or Pixel 5 have the same performance issue with MZD-AIO?
