### ISSUE TITLE
Pause on mute and Shorter Delay issues

### ISSUE THREAD

**Issue by Arakon** [Trevelopment/MZD-AIO#32]
I had 2 issues with AIO 2.8.1 on 59.00.545 EU:

- Shorter delay mod causes double beeps when navigating through menus using the commander stick. Almost every time I jump down or up one line. A third of the time it also skips a line. I'm thinking the 0.3 second delay may be a bit too short?

- Pause on mute mod causes me to be able to mute and pause a song from USB, but when attempting to unmute, a quick blip of the music plays, then mutes again. Pressing the mute button repeatedly will cause this to happen every time, always playing half a second or so of music before pausing again. Skipping to the next song or changing to FM and back to USB fixes this.

**Comment by Trevelopment** [comment]
- OK for the first thing you can apply the "No More Beeps" tweak to get rid of the beeps and for the shortened delay time I actually didn't make that tweak originally and have never had any complaints about it before so maybe if you want to make it a little longer before running the installer you can edit the delay time to fit your preference?  Lots of people do this when they want something a little bit different from how it is set up by default and I can help you find and change whatever you need to fix that for you but it would take me forever to make an option for every little nuance like how long the shorter delay time is.
- The second thing is known to be true for v70 but I didn't know it was also true for v59.00.545.  This behavior is because pause on mute is already built into the FW so when you apply the tweak you are pause-playing on mute and play-pausing on unmute.  So uninstall that tweak and I will change the install script to skip the installation for that version.
