### ISSUE TITLE
2.8.1 - 2.8.3 their function not work

### ISSUE THREAD

**Issue by aodbee** [Trevelopment/MZD-AIO#34]
2.8.1
-change wallpaper not work
-animation boot not work
2.8.3
-change wallpaper not work
-pause to mute not work
-animation boot not work

**Comment by Trevelopment** [comment]
What FW version?

**Comment by aodbee** [comment]
59.xxx bro

**Comment by Trevelopment** [comment]
Also, do you have log files?

**Comment by aodbee** [comment]
sorry for slow reply ;) yeah my current version 59.00.502A

**Comment by aodbee** [comment]
now i'm downgrade to 2.8.0 now its all work but old function lol

**Comment by aodbee** [comment]
i'm let  try again , i will keep log for you from usb bro

**Comment by aodbee** [comment]
WARNING: ROOT FILESYSTEM OVER 97% FULL!!

**Comment by aodbee** [comment]
[
[AIO_log.txt](https://github.com/Trevelopment/MZD-AIO/files/2636403/AIO_log.txt)
](url)

**Comment by Trevelopment** [comment]
Your FW version is 59.00.540 BTW but I see the mistake its because you install the swapfile.  When you install the swapfile it moves all the installer files to the log folder on the drive but it is suppose to come last.  It looks like background comes last so just dont install the swapfile and it will work .  You should not install the swapfile every time you install tweaks either way you are suppose to only install it once and LEAVE THE USB CONNECTED WHILE THE SYSTEM IS RUNNING.   DO NOT DISCONNECT THE USB WITH SAWPFILE WHILE THE SYSTEM IS RUNNING OR YOU MIGHT BREAK IT! IF YOU INSTALL SWAPFILE IT SHOULD BE ON THE USB YOU USE FOR MUSIC/VIDEOS AND SHOULD STAY CONNECTED MAKE SURE THE CAR IS OFF FOR AT LEAST 10 MINUTES BEFORE REMOVING USB DRIVE BECAUSE IT IS USING THE USB DRIVE FOR ACTIVE MEMORY (RAM).

**Comment by Trevelopment** [comment]
Can you also send me tweaks.sh because I just looked at my code and the background is added before the swapfile not after so you log doesnt make sense.

**Comment by Trevelopment** [comment]
Also I just compiled the same tweaks you did with v2.8.3 and it came out correctly I don't know why yours came out wrong

**Comment by aodbee** [comment]
thank you

**Comment by aodbee** [comment]
now it work install two time
 1. install normal include SWAPFILE  finish and go to  tweaks and unmount 
2. install again only wallpaper it work but pause to mute not work its show incompatible with fw 59.00.540 

Nota: rootfw always 90+ % rootfw size only 4xxMB
