### ISSUE TITLE
Music stutters once-twice per song on average

### ISSUE THREAD

**Issue by jspinella** [Trevelopment/MZD-AIO#4]
This started happening after installing the SSH_bringback, ID7_recovery scripts, Auto WiFi AP and Auto ADB scripts on a 2017 Mazda3 running 59.00.441 NA N firmware. I thought this issue would resolve itself after a reboot or two, but has not. 

I have since installed a few other tweaks (Android Auto, Pause on mute and No More Disclaimer), and the issue seems to have stayed the same as far as frequency (once-twice per song or so) goes. 

I have *not* tried Swapfile, but I am also not using Android Auto, simply using the built-in Bluetooth music player system with an iPhone 6s. I wonder if this issue "goes away" after switching to Android Auto (don't have an Android phone yet...). 

Here's the MZD_LOG.md from the recovery tweak install:

___
- *START!*
- Tweak Files Location: C:\Users\jspinella\Desktop\_copy_to_usb
- Delete old _copy_to_usb folder...
- ID7_recovery Pack Copied Successfully!
- USB Drive - D: SanDisk Cruzer USB Device

**Comment by Trevelopment** [comment]
You are saying that this is over Bluetooth right?  It has nothing to do with AIO or the autorun and recovery scripts it is an issue with the Bluetooth itself it is only a coincidence that it started happening after you installed the autorun scripts.   Pretty much it will fix itself or not regardless of what you do with AIO even if you uninstall everything it is not going to effect that in any way.

**Comment by jspinella** [comment]
Hey, thanks for the reply. I can't see it as a coincidence though, it started on the car ride I installed the recovery scripts, after 9 months of owning and driving the car without the issue, and has persisted since (about a week).

There is a "normal" music stuttering that has always happened but that's only when the CMU boots up (within the first 30 seconds or so after turning the car on). That stuttering always goes away once the CMU has finished booting up. It's hard to describe, but the stuttering that happens how is different from the car-start stutter. It's shorter/quicker and skips a second of the song, while the startup stutter is more of a brief pause but the song doesn't skip to a later part. 

Could it be an issue having installed the recovery items while driving/listening to music over bluetooth? I didn't see anywhere in instructions that I *couldn't* be driving/listening to music...

**Comment by Trevelopment** [comment]
Well if those scripts had anything to do with the Bluetooth or modified any files even remotely near the files that handle/control Bluetooth then I may think it is related but the fact is what you are saying is like the equivalent of saying I flushed my toilet and it turned the lights off...  There is just no way those 2 things can be correlated.

**Comment by Trevelopment** [comment]
Now Android Auto does add an audio stream to the entertainment control but that stream plays only audio from Android Auto and nothing else and also is half-way coded into the system I'm guessing because they were planing to use it for Car Play or AA when they were planning to officially release them.   Having said that the stream created by AA is on the entertainmentMuxUsb mux so it wouldn't effect Bluetooth sound at all which is on entertainmentMuxBtsa mux.  Anyways, either way the recovery scripts actually don't even do anything at all unless something has changed in your system so they can't effect anything because they aren't doing anything.

**Comment by Trevelopment** [comment]
I take that back the WiFi AP and adb reverse port do something and that is allow you to connect to your system via ssh and figure out what is going on :smile:

**Comment by jspinella** [comment]
I feel like those processes running in the background could be the cause. I did try streaming music through USB instead of Bluetooth and do not have the stuttering/skipping issues (but I didn't before flashing AIO stuff, too). Hopefully I don't have this issue with Android Auto streaming (it sounds like I won't based on the above). 

I cannot tell you how many times I was **sure** a thing couldn't be the issue and it ended up being the thing. Removing the recovery tweaks would remove any doubt, although I prefer to mess with the CMU as little as possible. I'll wait and see how Android Auto does.

**Comment by Trevelopment** [comment]
Try it I have ran the tweak installer on my own car many hundreds of times over the past couple years and had all kids of crazy issues but I can always the get my system back to normal in most cases better than it was before and I wrote all that experience into the installer so you will most likely end up with a more optimized system after installing tweaks. But by all means try it there is only 750 MB of RAM so if the issue is just one stutter per song then maybe it just because of that.

**Comment by jspinella** [comment]
Uninstalling the WiFi hotspot fixed the issue. It appears that WiFi will interfere with Bluetooth (potentially a separate issue from the lack of EMI shielding issue on earlier Mazda CMUs). I imagine most people with AIO tweaks use Android Auto, so maybe this issue has flown under the radar? Maybe I just missed it. In any event, who needs WiFi, anyway!

**Comment by Trevelopment** [comment]
Oh my bad I kinda did know about that I should have mentioned it but I don't think I made the connection that you were using the Bluetooth and WiFi together. I was having an off day or something.

**Comment by jspinella** [comment]
No worries! Do you know why the WiFi interferes with Bluetooth? I've never heard of this being an issue, and I'm kind of assuming it's due to a lack of EMI shielding? That being said, my WiFi connection is strong, whereas the EMI shielding issue seems to have the opposite going on.

**Comment by hansaya** [comment]
WIFI and Bluetooth uses the same frequency. Car system most likely going to have a one modem(using the same antenna) with WIFI and Bluetooth built in. Modem rapidly switches its radio between two if it is using both at the same time, but this should not be a problem since manufacture of those radios should handle it. However I haven't seen a inside of the Mazda system yet so I cannot tell whats going on. Other thing to note is, your phone or any other near by 2.4ghz radio could interfere when they disregard Bluetooth channels. 

Have you monitor the system usage during shuttering? You could enable the inlay by pressing Music + Back + Pwr/Mute. http://mazda3revolution.com/forums/2014-2017-mazda-3-skyactiv-audio-electronics/54722-accessing-infotainment-diagnostics-menu.html 
This might give you an clue is to whats going on.

**Comment by jspinella** [comment]
Ah cool, thanks! It did almost seem like random interference, so the theory that neighboring cars’/homes’ WiFi devices are interfering makes sense. It sucks that WiFi/BT share a radio + antenna, it would have been very cheap to have them be dedicated.

This would pose an issue for my other repo issue (feature request) for Android Auto over WiFi.

**Comment by jspinella** [comment]
I’ve since removed the WiFi tweak but I will keep the system monitor toggle in mind if I ever install it again.

**Comment by juanmre** [comment]
Hi, thanks for the prompt response.
Is a CX-5, sold in Mexico as 2018, but i guess it was really late 2017 (new grill design).
CMU version is 59.99.446 NA N.  I used AIO 2.8.2 with the latest version of AIO AA.
Just after your message I went downstairs and tested with BT off in my phone and only the cable... It worked exactly the same, and the audio problem is when zooming, routing or interacting with Waze or GMaps... by the way my sound source is Spotify, with Offline content and streamed content, the behavior is the same. Im not in the navigator screen, since there is no routing the audio is smooth without any problem.
Thanks !

**Comment by jspinella** [comment]
Thanks for the info.. I would open a new issue, this one has been closed for some time, and isn't the same issue (although it is similar). It kind of sounds like the CMU/phone's CPU doesn't have enough power to support playing music and redrawing the Waze/Google Maps "picture".  

What kind of phone do you have? If it's some low-end  phone I would expect something like this to happen.

**Comment by juanmre** [comment]
Hi,
That seems to be the issue, exactly when drawing in the screen... Im using a Samsung S9+. In the beginning i had problems with navigation due to lack of GPS, but it was the power saving mode on the phone, now disabled, locations works fine.
I tried to take out Android Auto, Waze and Maps out of any power saving mode in the phone and test again, but unfortunately, same results.

I wonder if is really something in my own setup, because I haven't found more references to this problem.

Thanks!

**Comment by lubokkanev** [comment]
Adding an update to this old thread: 
I think it's the CMU CPU, not the phone because it does the same thing for me with a newer phone.
Here's a more recent issue about that #139.
