### ISSUE TITLE
Google Assistant is launched when control knob is pushed to the right

### ISSUE THREAD

**Issue by jcspradley** [Trevelopment/MZD-AIO#43]
Just the like title says, when I push the control knob to the right it launches Google Assistant. It's mostly not a problem except for that I'm unable to move the selection to the new "Now Playing" button that looks like three vertical bars which is over on the right side. Other than that it works great. 

Thank you!

I'm using a Pixel 2 running Pie with latest Feb update. In the car I'm using 2.8.3.

**Comment by Trevelopment** [comment]
I don't think you understand what is happening here because this is just how Android Auto works (the app on your phone) we have just associated the Command-knob-tilt-right with Android Auto D-pad Right the functionality of "Right" is determined by the app on your phone not on your headunit.  
https://github.com/Trevelopment/headunit/blob/master/mazda/outputs.cpp#L289-L291
There is a "Command-knob-only" mode but we have not been able to figure out how to switch the functionality style.
https://github.com/gartnera/headunit/issues/141

**Comment by jcspradley** [comment]
Gotcha, I appreciate the quick response and a huge thanks for all of your hard work!
