### ISSUE TITLE
Brick after System Restore

### ISSUE THREAD

**Issue by coo79** [Trevelopment/MZD-AIO#47]
System has brick after I run "System Restore" in AIO Tweaks APP (AIO 2.8.2).
After power-on, screen continues to display the Mazda logo forever.

I tried "FULL SYSTEM RESTORE" script and re-install AIO 2.8.4, but situation did not change.

**Comment by Trevelopment** [comment]
Run "Backup JCI Folder" and share with me over google drive or something similar.  If you can still run tweaks you can fully recover but I need to make you a custom script.

**Comment by Trevelopment** [comment]
OK coll lets move this convo to email trez@mazdatweaks.com by the time you email me I will have your recovery script ready

**Comment by Trevelopment** [comment]
Hey here is your recovery https://drive.google.com/open?id=1Bw1l_65n0Ur3MmR__Daj5cBTNWFenYii
I am going to take that down in a few hours because I dont want anyone else to run it since it is specifically written for you and your issue only so if you dont get it by then you can email me and Ill share it again with you.
