### ISSUE TITLE
Adding border to StatusBar Speedometer text

### ISSUE THREAD

**Issue by mellda** [Trevelopment/MZD-AIO#48]
Hello,

I like StatusBar Speedometer feature very much. Single values are visible all the time and not disturbing me. Is it possible to use a kind of border for the text? For example I use Coolant Temperature as a Main Value. But when I open Android Auto (the official one), I cannot read the value because there are some white pictures in background. Either border/shadow or a small black box? I had a look on the compiled code and identified the template for creating StatusBar. If I am righ, it is SpeedBarTmplt.js. I am not sure what element should I edit. Either

1. the div which is parent for all statusbar values (div with id barlayout), or
2. the div for each value separately

Is it ok when I define the border on the parent div element which wraps all the values? Or is it better to add it to each of them separately? I know the Coolant Temperature changes its font color according to the measured temperature value. Blue/yellow/white. Black border for yellow/white, white border for the blue. I think it would be better to add it separately because I don't know how the other values are displayed.

**Comment by Trevelopment** [comment]
One thing you can do right out of the box is add shadow with the "text colors"tweak or color to the text with the  "statusbar tweaks".  if you want to make edits yourself I would suggest not editing any JavaScript files especially SpeedBarTmplt.js because a mistake in that file will brick your system.  Plus everything youre asking for can be done with CSS and you can just add it to the end of this file with the rest of the statusbar speedometer CSS [StatusBarSpeedometer.css](https://github.com/Trevelopment/MZD-AIO/blob/master/app/files/tweaks/config/speedometer/jci/gui/apps/_speedometer/css/StatusBarSpeedometer.css)
the statusbar speedometer is actually on top of everything so it is not even under barlayout.  I dont know how much you know about DOM but the only reason you can even see it with AA running is because it is outside of the main div that holds the GUI.  Anyways that CSS file should be self explanatory if you know CSS the main div id is `#SbSpeedo` with the main value in `#SbSpeedo .SbMain` and the 2 smaller values are `#SbSpeedo .SbVal1` and `#SbSopeedo .SbVal2`
You should probably add your custom CSS to the bottom of the file but I guess if you know what you are doing you can do whatever.  Also another tip I will offer is to use outlines instead of borders.  A border will increase the width & height of the div its around and might break some formatting if you don't compensate for that while outlines wont affect the div size.

**Comment by mellda** [comment]
Great. Thak you. The text colors tweak works. A small side effect is that the shadow was applied to the text of tabs in settings menu and it does not look as good as before. I did not understand how to use the statusbar tweak.

Good to know I can brick my system by wrong customization. I will be very carefull.
