### ISSUE TITLE
Caught unhandled exception: cannot read path of 'undefined'

### ISSUE THREAD

**Issue by hudo** [Trevelopment/MZD-AIO#61]
When compiling files to output folder, it crashes when writing tweaks.sh (file has 50kb of content, so something has been written)
Same as https://github.com/Trevelopment/MZD-AIO/issues/52
Looks like standard null reference exception in Javascript.
OS is Windows 10 1903, app version is 2.8.4-1

**Comment by Trevelopment** [comment]
OK this is what is happening, drivelist (npm package) is returning an object containing a drive that has no path, hence drive.path === undefined.  I found that this happens when you have a drive plugged in but unmounted or something like that or maybe a virtual drive that is unmounted or an unused partition.  For the next AIO I had to rewrite all the USB drive stuff because drivelist changed and now uses promises and I put in a check for undefined paths.

**Comment by Trevelopment** [comment]
It actually happens right after tweaks.sh is done being written on the next step which is to detect USB drives.  So a workaround for now is to make sure you don't have any drives that are unmounted but still connected or virtual drives that are connected but don't have a path or anything out of the ordinary like that with your detectable drives.
