### ISSUE TITLE
Unhandled exception when generating a USB

### ISSUE THREAD

**Issue by JBanks** [Trevelopment/MZD-AIO#68]
This error happens whenever I try to create a USB.  It creates most, if not all of the necessary files before the error closes the program.

![image](https://user-images.githubusercontent.com/453768/68637402-84701980-04cc-11ea-8c00-fa7128149c6e.png)

**Comment by Trevelopment** [comment]
This I have a fix for in the next version but it is because you have a drive that is connected but not mounted so the drive is found and returns an object but that object is undefined because the drive isn't mounted.  This could be a drive that you left connected after ejecting or it could be a virtual drive too.  This was also a problem with Drivelist, the npm package used to find disk drives, but in the newer versions of Drivelist it has changes to a promise based system plus I still double check for the possibility of undefined drives.

**Comment by Trevelopment** [comment]
And it has completed creating the files at that point so if you can't figure it out you can always manually copy the files.
