### ISSUE TITLE
Screen interference/static/flashing

### ISSUE THREAD

**Issue by ryansomerfield1** [Trevelopment/MZD-AIO#7]
Hey there!
    Ever since I installed the recovery pack I've been having pretty significant issues with my CMU - on bootup there is a significant amount of signal noise that shows up all over the screen - the screen will cut out occasionally, too. It's caused the CMU to crash on a fairly regular basis as well.

For some reason my car is also now showing up as a permanent hotspot - wifi is always running (I have no idea if this is related).

Is there a way to flash the entire CMU back to factory settings (including removal of the recovery script) so I can do a reinstall? Or have you seen this issue before?

thanks.

**Comment by Trevelopment** [comment]
Whats you FW version?  All the autorun files are in one folder so you definitely don't need to flash your entire CMU to get rid of one folder dude.
To uninstall ie. delete that folder you just run the same script as the install script but when it prompts you for input and gives you 3 choices: "install", "uninstall", or "skip" you choose "uninstall" instead of "install"
When you select to compile the installer for the autorun scripts in AIO there are 3 additional options you can choose, one is the hotspot that would be "Auto WiFi AP" (WiFi Access Point = hotspot) so you if you don't want that then leave that option unchecked when you install.

**Comment by ryansomerfield1** [comment]
Thanks for the suggestions. Disabling the WiFi cleared it all up. Greatly appreciate it!
