### ISSUE TITLE
Android Auto doesn't start

### ISSUE THREAD

**Issue by yonist** [Trevelopment/MZD-AIO#8]
Hi,

I've a Mazda 3 Active 2017 (European model)

After applying different tweaks without a problem I install Android Auto but it fails to load. I see a log message screen with the message:
"failed to load plugin /usr/lib/gstreamer-0-10/....." (see the attached image for the full message)

Any idea what can cause it? 

Thanks
![20180210_180511](https://user-images.githubusercontent.com/499992/38306764-3e17e948-381a-11e8-899c-25ed23a85e2c.jpg)

**Comment by Trevelopment** [comment]
Everyone gets those errors they are just Gstreamer errors.  You can use the multicontroller to scroll that textbox and when you get to the end you will see something like "nothing found waiting to connect" because it is waiting for you to plug your Android phone to the car's USB.  If your phone is already connected then your USB cable is the problem and that issue is fixed by using a better quality USB cable.
