### ISSUE TITLE
Serial Access how to block it again without updating to a higher version of Mazda software

### ISSUE THREAD

**Issue by trippplelift** [Trevelopment/MZD-AIO#99]
Hello,

I wonder if it's possible to get rid off serial access just by sending a similar command just with opposite effect? I know it's possible to update to 70.00.335 and it will happen anyway but I am curious if there is a faster method. So in other words I want to do again serial connection through putty and get back to starting point without access to instal AIO Tweaks.

Thanks in advance :) If you can help me I can tip you through PayPal

**Comment by Trevelopment** [comment]
I don't really understand what you are trying to do.  To restore your system the the starting point ie. remove all the tweaks there is a script you can run but there isn't one command to do it because it is a very complicated set of things it is looking for to remove.  If you are trying to block yourself from serial access you can just install SSH_Bringback but open the password file and put in some nonsense , then you will be blocked because you wont know the password.  Warning if you do that you will never be able to access the file system again.
